import Head from 'next/head';
import Hero from '../components/hero';
import Features from '../components/features';
import Stats from '../components/stats';
import TestimonialCard from '../components/testimonial-card';
import CTA from '../components/cta';
import Layout from '../components/layout';
import Image from 'next/image';

export default function Home() {
  return (
    <Layout title="Home | ColdXposure" description="" keywords="">
      <Head>
        <title>ColdXposure | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="">
        <Hero />
        <Features />
        <TestimonialCard />
        <Stats />
        <div className="py-12 sm:pb-20 sm:pt-12 lg:pb-28">
          <CTA />
        </div>
      </main>
    </Layout>
  );
}
